{% set version = "1.16.0" %}
{% set sha256 = "93b9553e3ee544e05395022bea67e6d600f8f3eb680950ec7cf73c0f55162487" %}

package:
  name: thrust
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/thrust/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [(linux or win) and (cuda_compiler_version != "11.2")]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [not osx]
    - cmake >=3.15
    - make
  run_constrained:
    - cub {{ version }}.*
    - cuda-cccl <0.0.0a0
    - cuda-cccl-impl <0.0.0a0
    - cuda-cccl_{{ target_platform }} <0.0.0a0

test:
  commands:
    - test -e "$PREFIX"/include/thrust/version.h  # [not win]
    - test -e "$PREFIX"/lib/cmake/thrust/thrust-config.cmake  # [not win]
    - if not exist "%LIBRARY_INC%"\thrust\version.h exit 1  # [win]
    - if not exist "%LIBRARY_LIB%"\cmake\thrust\thrust-config.cmake exit 1  # [win]

about:
  home: https://github.com/NVIDIA/thrust
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thrust is a C++ parallel programming library which resembles the C++ Standard Library.
  description: |
    Thrust's high-level interface greatly enhances programmer productivity while enabling
    performance portability between GPUs and multicore CPUs. Interoperability with established
    technologies (such as CUDA, TBB, and OpenMP) facilitates integration with existing software.
    Develop high-performance applications rapidly with Thrust!
  doc_url: https://thrust.github.io/
  dev_url: https://github.com/thrust/thrust

extra:
  recipe-maintainers:
    - rongou
    - kkraus14
    - leofang
